package modelo.entidad;
// Generated 3/10/2021 11:42:36 PM by Hibernate Tools 4.3.1



/**
 * Campana generated by hbm2java
 */
public class Campana  implements java.io.Serializable {


     private Integer idCampana;
     private String descripcion;

    public Campana() {
    }

    public Campana(String descripcion) {
       this.descripcion = descripcion;
    }
   
    public Integer getIdCampana() {
        return this.idCampana;
    }
    
    public void setIdCampana(Integer idCampana) {
        this.idCampana = idCampana;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


