package modelo.entidad;
// Generated 3/10/2021 11:42:36 PM by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int cedula;
     private String nombre;
     private String direccion;
     private String ciudad;
     private Long telefono;
     private Long celular;
     private String correo;

    public Cliente() {
    }

	
    public Cliente(int cedula) {
        this.cedula = cedula;
    }
    public Cliente(int cedula, String nombre, String direccion, String ciudad, Long telefono, Long celular, String correo) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.direccion = direccion;
       this.ciudad = ciudad;
       this.telefono = telefono;
       this.celular = celular;
       this.correo = correo;
    }
   
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public Long getCelular() {
        return this.celular;
    }
    
    public void setCelular(Long celular) {
        this.celular = celular;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


