package modelo.entidad;
// Generated 3/10/2021 11:42:36 PM by Hibernate Tools 4.3.1



/**
 * Difuncion generated by hbm2java
 */
public class Difuncion  implements java.io.Serializable {


     private Integer idDifuncion;
     private Integer cedulaCliente;
     private String nombreCliente;
     private String campana;
     private Integer idNotificacion;
     private String inscrito;

    public Difuncion() {
    }

    public Difuncion(Integer cedulaCliente, String nombreCliente, String campana, Integer idNotificacion, String inscrito) {
       this.cedulaCliente = cedulaCliente;
       this.nombreCliente = nombreCliente;
       this.campana = campana;
       this.idNotificacion = idNotificacion;
       this.inscrito = inscrito;
    }
   
    public Integer getIdDifuncion() {
        return this.idDifuncion;
    }
    
    public void setIdDifuncion(Integer idDifuncion) {
        this.idDifuncion = idDifuncion;
    }
    public Integer getCedulaCliente() {
        return this.cedulaCliente;
    }
    
    public void setCedulaCliente(Integer cedulaCliente) {
        this.cedulaCliente = cedulaCliente;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getCampana() {
        return this.campana;
    }
    
    public void setCampana(String campana) {
        this.campana = campana;
    }
    public Integer getIdNotificacion() {
        return this.idNotificacion;
    }
    
    public void setIdNotificacion(Integer idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public String getInscrito() {
        return this.inscrito;
    }
    
    public void setInscrito(String inscrito) {
        this.inscrito = inscrito;
    }




}


